# Site settings
description: From Clash of Clans
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://rwwcoc.github.io" # the base hostname & protocol for your site 

# User settings
username: rwwcoc
user_description: Red War Wizards
user_title: Red War Wizards
email: rwwcoc@gmail.com
github_username:  rwwcoc

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
